### ISSUE TITLE
[Node SDK] Hub's requests time out a lot during load testing

### ISSUE THREAD

**Issue by ktrz-sre-is** [StanzaSystems/stanza-js#100]
Under the load test for the `express-demo` app a lot of hub request time out and therefore it passes though a significant amount of requests.

This is likely happening because of requests queueing but hub not providing enough tokens to flush the queue within the default timeout (1000ms)

**Comment by sre-is-josebiro** [comment]
@ktrz-sre-is Is this still happening?

**Comment by ktrz-sre-is** [comment]
not relevant anymore
