### ISSUE TITLE
Fail open in browser

### ISSUE THREAD

**Issue by maggiepint** [StanzaSystems/stanza-js#11]
It is critical that failure of Stanza does not block the user experience of the webpage. To achieve 'fail open' requests to Stanza that exceed 1 second need to short circuit and reset the current context to 'open' (no features modified).

The 1 second should probably be configurable in the `StanzaConfig.ts`

**Comment by ktrz-sre-is** [comment]
Update: As of today it does fail open if the hub request fails (but it doesn't have timeout built-in).

TODO: Introduce configurable timeout to polling requests
