### ISSUE TITLE
Vendor StanzaComponent

### ISSUE THREAD

**Issue by maggiepint** [StanzaSystems/stanza-js#166]
Right now our docs imply that you can import StanzaComponent from our React libraries, but in fact you have to move it over from our samples yourself. Can we correctly vendor StanzaComponent to be importable from the react library?

**Comment by ktrz-sre-is** [comment]
I think the current implementation of StanzaComponent that we have embedded into the Next with Stripe example is too bare-bones. I would love to discuss what exact MVP functionality we want out of that so that we ship some more utility.

Let's discuss at todat's FE sync if possible

**Comment by ktrz-sre-is** [comment]
I think the current implementation of StanzaComponent that we have embedded into the Next with Stripe example is too bare-bones. I would love to discuss what exact MVP functionality we want out of that so that we ship some more utility.

Let's discuss at  FE sync if possible
