### ISSUE TITLE
[Node SDK] GRPC doesn’t seem to work for dev hub

### ISSUE THREAD

**Issue by ktrz-sre-is** [StanzaSystems/stanza-js#98]
In `express-demo` sample app we're using `useRestHubApi: true` flag as the Hub communication with dev's hub seem to not work correctly.

Investigate and fix the underlying issue so that we can use gRPC consistently.

**Comment by sre-is-josebiro** [comment]
@ktrz-sre-is is this still needed?

**Comment by ktrz-sre-is** [comment]
Can't reproduce
